version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: events_user
      POSTGRES_PASSWORD: eventspassword
      POSTGRES_DB: events_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fastify:
    build: .
    command: pnpm fastify
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://events_user:eventspassword@postgres:5432/events_db
    ports:
      - "3001:3001"

  api:
    build: .
    ports:
    - "3000:3000"
    depends_on:
      - postgres
      - fastify
    environment:
      DATABASE_URL: postgres://events_user:eventspassword@postgres:5432/events_db
      FASTIFY_URL: http://fastify:3001
    command: sh -c "npx tsx src/server/db/migrations/migrate.ts && pnpm start"

volumes:
  postgres_data: